name: deploment test

on:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        default: 'none'
        description: package version
      test:
        type: boolean
        default: false
        description: A pointless checkbox.
  push: 
    branches:
      - main
jobs:
  wait:
    name: Run Api
    runs-on: ubuntu-latest
    steps:
    - name: Generate UUID
      id: generate_uuid # Assign an ID to the step to access its output
      run: |
        echo "::set-output name=uuid::$(uuidgen)"

    - name: Use UUID
      run: |
        echo "Generated UUID: ${{ steps.generate_uuid.outputs.uuid }}"
        
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: Saturday-Morning-Publishing-LLC
        repo: demo-backend-org
    - name: Use the token
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        echo ${{ steps.generate-token.outputs.token }}
        gh api octocat
    - name: Build Api ${{inputs.version}}
      run: sleep 10 
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        github_token: ${{ steps.generate-token.outputs.token }}

    - name: Modify a file     
      run: |
        #update file
        jq '.["peerDependencies"]["@test/models"] = "${{inputs.version}}"' package.json > ${{steps.generate_uuid.outputs.uuid}}.json && mv ${{steps.generate_uuid.outputs.uuid}}.json package.json

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        token: ${{ steps.generate-token.outputs.token }}
        message: 'Automated: Update package.json'
        push: true
        add: 'package.json' # Specify the file(s) to add