name: deploment test

on:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        default: 'none'
        description: package version
      test:
        type: boolean
        default: false
        description: A pointless checkbox.
  push: 
    branches:
      - main
jobs:
  wait:
    name: Run Api
    runs-on: ubuntu-latest
    steps:
    - name: Build Api ${{inputs.version}}
      run: sleep 10 
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Modify a file
      run: echo "This is updated content."
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions Bot
        author_email: github-actions[bot]@users.noreply.github.com
        message: 'Automated: Update package.json'
        add: 'package.json' # Specify the file(s) to add