name: Lint source code
on:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        default: 'none'
        description: package version
  push: 
    branches:
      - main

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Modify a file
        run: echo "This is updated content." >> test.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: sirmontman
          committer_email: sirmontman@gmail.com
          message: 'Your commit message'
          add: 'test.txt'